apiVersion: v1
kind: Service
metadata:
  name: sre-worker
  namespace: sre
  labels:
    app: sre-worker
spec:
  selector:
    app: sre-worker
  ports:
  - name: metrics
    port: 8001
    targetPort: 8001
    protocol: TCP
